### ISSUE TITLE
Error: logical subscript contains NAs (looks like could not annotate peak locations)

### ISSUE THREAD

**Issue by edfajardo** [al-mcintyre/DEQ#1]
The program finished with an error:

Error: logical subscript contains NAs
In addition: Warning messages: (omitted)

After some additional investigation, this might be related to the genome/gtf file.  The dataset is from mouse and I am using the gtf file from ensembl (mm10.ensGene.gtf).   The the initial variables of the peaks object look like this:

 >$peaks
GRanges object with 44562 ranges and 11 metadata columns:
            seqnames            ranges strand |        name        exon
              \<Rle>         \<IRanges>  \<Rle> | \<character> \<character>
      peak1        1   3215477-3215830      + |       peak1        \<NA>
      peak2        1   3221883-3222122      + |       peak2        \<NA>
      peak3        1   3242487-3242763      + |       peak3        \<NA>
      peak4        1   3243106-3243396      + |       peak4        \<NA>
      peak5        1   3250698-3250935      + |       peak5        \<NA>
        ...      ...               ...    ... .         ...         ...
  peak44558        Y 90742797-90743482      + |   peak44558        \<NA>
  peak44559        Y 90743894-90744093      + |   peak44559        \<NA>
  peak44560        Y 90793317-90793756      + |   peak44560        \<NA>
  peak44561        Y 90811178-90812825      + |   peak44561        \<NA>
  peak44562        Y 90816202-90816427      + |   peak44562        \<NA>
                 intron        utr5       utr5*        utr3       utr3*
            \<character> \<character> \<character> \<character> \<character>
       peak1        \<NA>        \<NA>        \<NA>        \<NA>        \NA>
     peak2        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
      peak3       \ <NA>        \<NA>        \<NA>        \<NA>        \<NA>
      peak4        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
      peak5        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
        ...         ...         ...         ...         ...         ...
  peak44558        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
  peak44559       \ <NA>        \<NA>        \<NA>        \<NA>        \<NA>
  peak44560        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
  peak44561        \<NA>        \<NA>        \<NA>        \<NA>        \<NA>
  peak44562       \ <NA>       \ <NA>        \<NA>        \<NA>        \<NA>
            intergenic       annot main.gene main.gene.id
             \<logical> \<character> \<logical>    \<logical>
      peak1       TRUE  intergenic      \<NA>         \<NA>
      peak2       TRUE  intergenic      \<NA>         \<NA>
      peak3       TRUE  intergenic      \<NA>         \NA>
      peak4       TRUE  intergenic      \<NA>         \<NA>
      peak5       TRUE  intergenic      \<NA>         \<NA>
        ...        ...         ...       ...          ...
  peak44558       TRUE  intergenic      \<NA>         \<NA>
  peak44559       TRUE  intergenic      \<NA>         \<NA>
  peak44560       TRUE  intergenic      \<NA>         \<NA>
  peak44561       TRUE  intergenic      \<NA>         \<NA>
  peak44562       TRUE  intergenic      \<NA>         \<NA>
  -------
  seqinfo: 22 sequences from an unspecified genome; no seqlengths

>$overlaps
[1] feature   name      gene_name
\<0 rows> (or 0-length row.names)

So it looks like it could not match the location of a peak with a particular gene.

For completion, the top of the following variables look like this (not sure why the NA values for pval and adj.pval in some peaks/genes:

peak.counts:

P10_ctr.bam	P18_ctr.bam	P48_ctr.bam	P10_ctr.merip.bam	P18_ctr.merip.bam	P48_ctr.merip.bam	P10_noMettl14.bam	P18_noMettl14.bam	P48_noMettl14.bam	P10_noMettl14.merip.bam	P18_noMettl14.merip.bam	P48_noMettl14.merip.bam
peak1	29	14	16	59	42	35	19	18	17	11	17	0
peak2	4	8	10	9	5	12	3	9	1	2	3	0
peak3	0	2	1	7	25	9	1	0	0	4	1	48
peak4	0	1	1	7	13	3	0	1	0	15	5	1
peak5	4	2	2	7	8	2	4	2	3	11	1	0
peak6	6	19	12	6	6	1	4	6	6	2	5	173

gene.counts:

P10_ctr.bam	P18_ctr.bam	P48_ctr.bam	P10_noMettl14.bam	P18_noMettl14.bam	P48_noMettl14.bam
ENSMUSG00000102693	0	0	0	0	0	0
ENSMUSG00000064842	0	0	0	0	0	0
ENSMUSG00000051951	513	375	377	430	261	285
ENSMUSG00000102851	9	11	10	7	5	3
ENSMUSG00000103377	6	14	5	5	12	4
ENSMUSG00000104017	4	2	7	3	5	4
ENSMUSG00000103025	4	11	10	10	6	7
ENSMUSG00000089699	4	3	5	1	2	6
ENSMUSG00000103201	1	22	25	6	9	4

peak.de:

peak.l2fc	peak.p	peak.padj
peak1	-1.67341657435476	0.148387931542962	0.996843961582788
peak2	-1.83535374311587	0.217938419923026	NA
peak3	1.06905802400045	0.436821611779313	0.996843961582788
peak4	0.434711971036041	0.735856828666445	NA
peak5	0.0410108544099603	0.98025271421217	NA

gene.de:

gene.l2fc	gene.p	gene.padj
ENSMUSG00000102693	NA	NA	NA
ENSMUSG00000064842	NA	NA	NA
ENSMUSG00000051951	-0.395917486181937	0.118312520014552	0.615789730185453
ENSMUSG00000102851	-1.0261528515366	0.162465513218275	0.698211601649789
ENSMUSG00000103377	-0.27116537774478	0.76605952647633	0.995022010614611
ENSMUSG00000104017	-0.098912248225897	0.918869708541386	NA

Thanks. 

Eduardo

PS. I hope the formatting looks OK.  It was not easy.

**Comment by al-mcintyre** [comment]
Hi Eduardo, 

Can you run `traceback()` after the error occurs and send the details? As far as I can tell, the chromosome names shouldn't be an issue unless there's a mismatch between your alignment/peak files and your gtf -- does the gtf also use "1" rather than "chr1"? 

Thanks!

**Comment by edfajardo** [comment]
Yes, that's the problem: the gtf file has chromosome ids with "chr" in it, as in chr1.  The alignments just show "1" in the case of chr1.  I am processing the new alignments, run with new indices to correct the chromosome names, and see what happens.  I'll let you know at the end of the day.  Our day, that is :) 

Thanks!

**Comment by edfajardo** [comment]
OK, problem solved.  The program ran to completion with no errors.  Let me give some details that might help somebody else. This experiment was done in mouse, and  I did the alignments with HISAT2.  Instead of making my own indices, I download the indices prepared by the John Hopkins people (this is where the program comes from).  Initially I downloaded the grcm38_tran indices (https://cloud.biohpc.swmed.edu/index.php/s/grcm38_tran/download).  As I later found out, after getting the errors described above, the chromosome ids in these indices don't follow the standard format, chrXX, where XX is the chromosome number (or X or Y).  Instead, the "chr" part is dropped.  To run DEQ, you have to provide a gtf file for the appropriate genome.  I used the ensembl file for mouse, mm10.ensGene.gtf (the refseq gtf, mm10.refGene.gtf, does not work).  The chromosome ids in the gtf files are in the standard format, i.e., chrXX, as details above.  So when DEQ tries to map the peaks to the appropriate region of the genome, it can't because the peak bedfiles will not have "chr" in the chromosome ids for the peak coordinates.  This is what causes the error. 

The solution was to make my own indices from the mm10 genomic sequences.  There are other pre-made indices available (ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/mm10.tar.gz) but I have not tried them.  The human hg38 (https://cloud.biohpc.swmed.edu/index.php/s/hg38_tran/download) or the  rat rn6 indices (ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/rn6.tar.gz) don't have this problem. 

I know this is a long message but I wanted to provide as much detail as possible.  Thank you for your help. 

Eduardo

**Comment by al-mcintyre** [comment]
Thanks Eduardo!
